FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY . .

RUN dotnet restore src/Swarm.Cluster/Swarm.Cluster.csproj

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "src/Swarm.Cluster", "--startup-project", "src/Swarm.Cluster", "--no-build"]
